name = "Microscopy"
uuid = "7e49bca2-f4a5-4c6e-849a-1c47e70e1da6"
authors = ["roflmaostc <fxw+git@mailbox.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
